# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ligra
email: dummy@cs.cmu.edu
description: A Lightweight Graph Processing Framework for Shared Memory
baseurl: "/ligra" # the subpath of your site, e.g. /blog
url: "http://laxmandhulipala.github.io" # the base hostname & protocol for your site
github_username: laxmandhulipala
sass:
  style: :compressed
  sass_dir: _css

# Build settings
markdown: kramdown
